### ISSUE TITLE
Reply to users on success

### ISSUE THREAD

**Issue by norbert** [eurucamp/eurucamp-activities-2012#16]
There should be a response when interest has been detected:

norbertc: @eurucamplive #imin DRN
eurucamplive: @norbertc great, see you there!

**Comment by pietia** [comment]
Too bad we CRON-like solution. Responses would have to be sent in 10-minute
cycles ... .

**Comment by jexp** [comment]
But can't we detect interests faster, immediately when a user enters them?

**Comment by pietia** [comment]
How? Does Twitter support PubSubHubBub? I was going to set it up on my own
server and use streaming api, but Alex wants it all on Heroku :P

**Comment by jexp** [comment]
Can't we actively poll twitter search without an API key for a few hashtags? That's how I did it most of the time.

**Comment by norbert** [comment]
@jexp that's what I'm doing to read all tweets but it's a separate codebase.

@pietia couldn't you just make the worker polling interval shorter? Assuming responses are sent immediately upon detection polling once a minute would be enough.

**Comment by pietia** [comment]
Your options are OK - that's what we do in Rake task which is being
triggered by "Heroku Scheduler".

@jexp https://github.com/jexp Do you use Heroku for this kind of stuff?
Cron? If you have some nice ideas - i'm all ears.

One of the reasons Alex decided to use "Heroku Scheduler" is
.... possibility to use it for free (using my own server would be free (for
Eurucamp) as well - but ... as i said - that wasn't my idea).

@norbert
AFAIR you cant trigger a job with 1 minute interval using Heroku Cron. We
would need to use something like this:
http://stackoverflow.com/questions/7315998/scheduling-a-job-every-minute-rails-3-1-on-heroku

Also, please see my message to @jexp (this part about money).

**Comment by pietia** [comment]
And BTW, Sorry if i will not answer on your messages today, i need to get up
at 5 to catch the plane to Berlin.

**Comment by myabc** [comment]
You can use your Hetzner box, if that makes sense. I had a preference to keep things centralized on Heroku, but I'm open - whatever is stable and will work, at this point.

**Comment by pietia** [comment]
Alright, decided to stay at heroku and use clockwork. More info in BC.
